# Generated by Django 3.1 on 2021-05-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commandes1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Enseigne1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=75)),
                ('nomEnseigne', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marque1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomMarque', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produits1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomProduits', models.CharField(max_length=50)),
                ('prix', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
