# Generated by Django 3.1 on 2021-05-17 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_creation_model_sansforeignkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseigne2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=75)),
                ('nomEnseigne', models.CharField(max_length=50)),
                ('marqueEnseigne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.marque1')),
            ],
        ),
        migrations.CreateModel(
            name='Produits2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('nomProduits', models.CharField(max_length=50)),
                ('prix', models.FloatField()),
                ('marqueProduits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.marque1')),
            ],
        ),
        migrations.DeleteModel(
            name='Enseigne1',
        ),
        migrations.DeleteModel(
            name='Produits1',
        ),
        migrations.AddField(
            model_name='enseigne2',
            name='produitPhare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.produits2'),
        ),
    ]
