# Generated by Django 3.1 on 2021-05-17 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_integration_champs_proprietaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseigne4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=75)),
                ('nomEnseigne', models.CharField(max_length=50)),
                ('marqueEnseigne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.marque2')),
                ('produitPhare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.produits2')),
            ],
        ),
        migrations.DeleteModel(
            name='Enseigne3',
        ),
    ]
