# Generated by Django 3.1 on 2021-05-18 08:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0006_bug_relatedname_proprietairesMarque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marque2',
            name='proprietaires',
            field=models.ManyToManyField(related_name='proprio', to=settings.AUTH_USER_MODEL),
        ),
    ]
