# Generated by Django 3.1 on 2021-05-18 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0007_bug_relatedname_proprietairesMarque2'),
    ]

    operations = [
        
    ]
