# Generated by Django 3.1 on 2021-05-18 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0008_PK_marque_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marque3',
            fields=[
                ('nomMarque', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('proprietaires', models.ManyToManyField(related_name='proprio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Marque2',
        ),
        migrations.CreateModel(
            name='Commandes4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Enseigne5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=75)),
                ('nomEnseigne', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produits3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('nomProduits', models.CharField(max_length=50)),
                ('prix', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Commandes3',
        ),
        migrations.DeleteModel(
            name='Enseigne4',
        ),
        migrations.DeleteModel(
            name='Produits2',
        ),
        migrations.AddField(
            model_name='produits3',
            name='marqueProduits',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.marque3'),
        ),
        migrations.AddField(
            model_name='enseigne5',
            name='marqueEnseigne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.marque3'),
        ),
        migrations.AddField(
            model_name='enseigne5',
            name='produitPhare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.produits3'),
        ),
        migrations.AddField(
            model_name='commandes4',
            name='produits',
            field=models.ManyToManyField(to='gestion.Produits3'),
        ),
        migrations.AddField(
            model_name='commandes4',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Propriétaire', to=settings.AUTH_USER_MODEL),
        ),
    ]
