# Generated by Django 3.1 on 2021-05-18 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0009_PK_marque_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commandes5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Enseigne6',
            fields=[
                ('adresse', models.CharField(max_length=75)),
                ('nomEnseigne', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Marque4',
            fields=[
                ('nomMarque', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('proprietaires', models.ManyToManyField(related_name='proprietaires', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produits4',
            fields=[
                ('description', models.CharField(blank=True, max_length=200)),
                ('nomProduits', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('prix', models.FloatField()),
                ('marqueProduits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.marque4')),
            ],
        ),
        migrations.RemoveField(
            model_name='enseigne5',
            name='marqueEnseigne',
        ),
        migrations.RemoveField(
            model_name='enseigne5',
            name='produitPhare',
        ),
        migrations.RemoveField(
            model_name='marque3',
            name='proprietaires',
        ),
        migrations.RemoveField(
            model_name='produits3',
            name='marqueProduits',
        ),
        migrations.DeleteModel(
            name='Commandes4',
        ),
        migrations.DeleteModel(
            name='Enseigne5',
        ),
        migrations.DeleteModel(
            name='Marque3',
        ),
        migrations.DeleteModel(
            name='Produits3',
        ),
        migrations.AddField(
            model_name='enseigne6',
            name='marqueEnseigne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.marque4'),
        ),
        migrations.AddField(
            model_name='enseigne6',
            name='produitPhare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.produits4'),
        ),
        migrations.AddField(
            model_name='commandes5',
            name='produits',
            field=models.ManyToManyField(to='gestion.Produits4'),
        ),
        migrations.AddField(
            model_name='commandes5',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Propriétaire', to=settings.AUTH_USER_MODEL),
        ),
    ]
