# Generated by Django 3.1 on 2021-05-20 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_changement_des_PK'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achat1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.commandes5')),
                ('produitAchetee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.produits4')),
            ],
        ),
    ]
