# Generated by Django 3.1 on 2021-05-20 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0013_liaison_avec_achat2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achat3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Commandes7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produits', models.ManyToManyField(to='gestion.Achat3')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Titulaire', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='achat3',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.commandes7'),
        ),
        migrations.AddField(
            model_name='achat3',
            name='produitAchetee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.produits5'),
        ),
    ]
