# Generated by Django 3.1 on 2021-05-20 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_valeur_achat_par_defaut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandes7',
            name='produits',
        ),
        migrations.RemoveField(
            model_name='commandes7',
            name='proprietaire',
        ),
        migrations.DeleteModel(
            name='Achat3',
        ),
        migrations.DeleteModel(
            name='Commandes7',
        ),
    ]
