# Generated by Django 3.1 on 2021-05-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_renomer_M2M_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandes6',
            name='achats',
        ),
        migrations.AddField(
            model_name='commandes6',
            name='produits',
            field=models.ManyToManyField(to='gestion.Produits5'),
        ),
        migrations.DeleteModel(
            name='Achat2',
        ),
    ]
